[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "buttonless"
opacity = 0.93
startup_mode = "Maximized"
blur = true

[window.padding]
x = 7
y = 7

[colors.primary]
foreground = '#8ba7a7'

[colors.normal]
black   = '#241b2f'
red     = '#fe4450'
green   = '#72f1b8'
yellow  = '#ffcc00'
blue    = '#af6df9'
magenta = '#fc199a'
cyan    = '#61e2ff'
white   = '#8ba7a7'

[colors.selection]
text       = '#8ba7a7'
background = '#463465'
