# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

# Custom color palette, see bottom of this file
palette = "fluoromachine"

# MODULES

[git_status]
style = "bold orange"

[aws]
disabled = true

[gcloud]
disabled = true

[palettes.fluoromachine]
fg = '#8BA7A7'
bg = '#262335'
alt_bg = '#241b2f'
currentline = '#463465'
selection = '#463465'
comment = '#495495'
cyan = '#61E2FF'
green = '#72f1b8'
orange = '#ff8b39'
pink = '#FC199A'
purple = '#AF6DF9'
red = '#fe4450'
yellow = '#FFCC00'
cursor_fg = '#282a36'
cursor_bg = '#8BA7A7'
sign_add = '#72f1b8'
sign_change = '#ff8b39'
sign_delete = '#fe4450'
error = '#fe4450'
warning = '#ff8b39'
info = '#61E2FF'
hint = '#61E2FF'
other = '#AF6DF9'
blankline = '#57367C'
active_blankline = '#7E0C4D'
inlay_hint = '#8C57C7'
