# Path to your oh-my-zsh installation.
export ZSH="/Users/lionc/.oh-my-zsh"

DEFAULT_USER="lionc"

# Uncomment the following line to disable auto-setting terminal title.
export DISABLE_AUTO_TITLE="true"

export LC_ALL=en_DE.UTF-8

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"

plugins=(
	autojump
	git
	macos
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Theme for ls, eza, tree etc
export LS_COLORS=$(vivid generate fluoromachine)

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

DOT_CONFIGS=$HOME/.config
source "$DOT_CONFIGS/zsh/aliases.sh"

# FNM Node Management
eval "$(fnm env)"

# OCaml
eval "$(opam env)"

# Atuin
eval "$(atuin init zsh)"

# Cargo
source $HOME/.cargo/env

# Carapace Completion
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
export CARAPACE_MARCH=1
#zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)

export PATH="/usr/local/bin:/Users/lionc/.deno/bin:/usr/local/sbin:$HOME/.jsvu:$HOME/go/bin:$PATH:$HOME/.config/zsh/scripts"

# Vim keybindings
bindkey -v

# Prompt (starship)
eval "$(starship init zsh)"
